# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            S/A sysadmin
tagline:          "Free school of systems administration"
description:      'Escola  <a href="http://jekyllrb.com" target="_blank">lliure</a> d`administració de sistemes" Made by <a href="http://sysadmin.cat" target="_blank">sysadmin.cat</a>.'
url:              http://lanyon.getpoole.com

author:
  name:           'sysadmin.cat'
  url:            https://sysadmin.cat

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
